### ISSUE TITLE
Writing News API fetch, retrieval function

### ISSUE THREAD

**Issue by Honsumal** [Honsumal/news-headline-aggregator#37]
User Story
As a developer, I want to pull out the title, description, and source from News API

Acceptance Criteria
When I put in my query and date
Then I get a response from news API

When I get a response from news API
Then I get the title, description, and source printed as a div under the headlines list

Update 1: Since API can only work from local host, we have to find a new one

**Comment by Honsumal** [comment]
User Story
As a developer, I want to pull out the title, description, and source from News API

Acceptance Criteria
When I put in my query and date
Then I get a response from news API

When I get a response from news API
Then I get the title, description, and source printed as a div under the headlines list

**Comment by pav1593** [comment]
We'll need to talk about the query/date requirement as I think the current API only pulled the current indicator news available on Stats Can the Daily. You can filter results by geo area and themes but can't search it.

**Comment by EllisJLC** [comment]
Problem: api link does not work with https, looking for alternative again.
